### ISSUE TITLE
.uasset files don't show up in explorer as blueprints/other assets

### ISSUE THREAD

**Issue by medflygg** [dannymcgee/Unreal_RotaryWingAircraft#1]
So the problem is that .uasset files don't show up in explorer as blueprints/other assets. When I try to copy them from plugin's content folder to project's folder nothing is working as well (except for the single .png file). But when I do copy them to another project, without the plugin installed all of the .uasset files are working properly (well, they are here, but they aren't working properly because there is no plugin)

**Comment by dannymcgee** [comment]
I'm assuming based on your troubleshooting that you _are_ seeing the `*.uasset` files on your file system? (If not, make sure you use `git clone` or `git submodule add` instead of downloading the ZIP directory — I'm pretty sure you did, but leaving the note here for the sake of search.)

If the files are definitely there but not showing up in the Unreal editor, can you check and see if you have "Show Plugin Content" enabled in your Content Browser settings?

[![Show Plugin Content](https://i.imgur.com/9nz3NAD.png)](https://i.imgur.com/9nz3NAD.png)

**Comment by medflygg** [comment]
> I'm assuming based on your troubleshooting that you _are_ seeing the `*.uasset` files on your file system? (If not, make sure you use `git clone` or `git submodule add` instead of downloading the ZIP directory — I'm pretty sure you did, but leaving the note here for the sake of search.)
> 
> If the files are definitely there but not showing up in the Unreal editor, can you check and see if you have "Show Plugin Content" enabled in your Content Browser settings?
> 
> [![Show Plugin Content](https://camo.githubusercontent.com/317f2bca19789516deb67d56b586aee7e1a107e1c53f4018b2b5a67993dd5a0d/68747470733a2f2f692e696d6775722e636f6d2f396e7a334e41442e706e67)](https://i.imgur.com/9nz3NAD.png)

Yeah, I've used git clone. I've already tried enabling "Show Plugin Content" , but that didn't help. I'm pretty sure that .uassets aren't recognized by unreal as there are no other gamemodes (in project settings) except for default ones. I've tried using it with 5.0.3 and 5.1.1. Maybe you could provide repository of a working .uproject with just a starter content and all the essential plugin blueprints? Also, thanks for a very quick response!

**Comment by dannymcgee** [comment]
No problem! You may also need to separately tick the same checkbox in the Project Settings' Game Mode input to get it to show up there. But I'll go ahead and put together a simple example project this evening and link to it here once it's uploaded.

**Comment by medflygg** [comment]
> 

Thanks, really appreciate that!

**Comment by medflygg** [comment]
Tried to get it working by placing it inside of engine's plugin folder and building (was following same algorithm that helped me to fix another plugin) it myself, no luck as well.

**Comment by dannymcgee** [comment]
Sorry I wasn't able to get to this last night. I'm working on it now, but one more thing to check in the meantime — can you verify that you have [Git LFS](https://git-lfs.com/) installed?

**Comment by dannymcgee** [comment]
Example project is uploaded [here](https://github.com/dannymcgee/Unreal_HeliExample)! Let me know if you're able to get it working.

**Comment by medflygg** [comment]
Example project didn't work at first either, as it turned out, the problem was with VS and msvc 14.29, it stubbornly installed the wrong version, which is why I could not create project files or build a plugin. I reinstalled Windows and now everything works. Thank you very much for your time and the work you did with the plugin.

**Comment by dannymcgee** [comment]
> I reinstalled Windows

Holy crap! I admire your dedication, but that is a bummer. I'm glad you got it working though! Feel free to open a new issue if you run into any other problems.
