### ISSUE TITLE
error rebuilding project

### ISSUE THREAD

**Issue by vincenzocas** [dannymcgee/Unreal_RotaryWingAircraft#5]
during rebuild to install the plugin, there are 3 errors:
D:\Unreal Project\TakeRecorderSample\Plugins\Gameplay\RotaryWingAircraft\Source\RotaryWingAircraft\Private\RWA\Heli.cpp(115): error C2059: errore di sintassi: ')'
11>D:\Unreal Project\TakeRecorderSample\Plugins\Gameplay\RotaryWingAircraft\Source\RotaryWingAircraft\Private\RWA\HeliMovement.cpp(31): error C2059: errore di sintassi: ')'
11>D:\Unreal Project\TakeRecorderSample\Plugins\Gameplay\RotaryWingAircraft\Source\RotaryWingAircraft\Private\RWA\HeliMovement.cpp(44): error C2059: errore di sintassi: ')'

**Comment by dannymcgee** [comment]
> during rebuild to install the plugin, there are 3 errors: D:\Unreal Project\TakeRecorderSample\Plugins\Gameplay\RotaryWingAircraft\Source\RotaryWingAircraft\Private\RWA\Heli.cpp(115): error C2059: errore di sintassi: ')' 11>D:\Unreal Project\TakeRecorderSample\Plugins\Gameplay\RotaryWingAircraft\Source\RotaryWingAircraft\Private\RWA\HeliMovement.cpp(31): error C2059: errore di sintassi: ')' 11>D:\Unreal Project\TakeRecorderSample\Plugins\Gameplay\RotaryWingAircraft\Source\RotaryWingAircraft\Private\RWA\HeliMovement.cpp(44): error C2059: errore di sintassi: ')'

It looks like all of those are coming from my log macros, which are pretty straightforward pass-throughs to `UE_LOG`. What version of Unreal Engine are you using?

**Comment by vincenzocas** [comment]
I’m using Unreal Entine 5.3

**Comment by dannymcgee** [comment]
@vincenzocas I haven't been able to reproduce this issue, but the plugin has been updated to UE 5.4 with #6 . Let me know if you still run into this issue and I'll reopen and investigate!
